name: Crazy Lady Knits
favicon: null
layout_spectrum: 0.8723307296168059
typography_spectrum: 0.16180258593522012
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6125392708927393
  lightness: 0.8710210947319865
  saturation: 0.2727661062963307
  rhythmicContrast: 0.2192262487951666
purpose: []
